import type { TeamMember } from "./types";

export const teams: TeamMember[] = [
  {
    id: "1",
    name: "Aria Voss",
    role: "Lead Designer",
    department: "product",
    status: "online",
    email: "aria@team.io",
    skills: ["Figma", "Design Systems", "Prototyping"],
    hireDate: "2021-03-15",
  },
  {
    id: "2",
    name: "Marcus Chen",
    role: "Senior Engineer",
    department: "engineering",
    status: "away",
    email: "marcus@team.io",
    skills: ["React", "TypeScript", "Node.js"],
    hireDate: "2020-11-02",
  },
  {
    id: "3",
    name: "Selin Kaya",
    role: "Product Manager",
    department: "product",
    status: "online",
    email: "selin@team.io",
    skills: ["Roadmapping", "User Research", "Agile"],
    hireDate: "2022-01-10",
  },
  {
    id: "4",
    name: "Jordan Ellis",
    role: "DevOps Lead",
    department: "engineering",
    status: "offline",
    email: "jordan@team.io",
    skills: ["AWS", "Docker", "CI/CD"],
    hireDate: "2019-07-22",
  },
  {
    id: "5",
    name: "Nour Hadid",
    role: "UI/UX Designer",
    department: "design",
    status: "online",
    email: "nour@team.io",
    skills: ["Figma", "Wireframing", "User Testing"],
    hireDate: "2023-04-18",
  },
  {
    id: "6",
    name: "Felix Braun",
    role: "QA Engineer",
    department: "engineering",
    status: "offline",
    email: "felix@team.io",
    skills: ["Automation Testing", "Cypress", "Test Planning"],
    hireDate: "2021-09-30",
  },
  {
    id: "7",
    name: "Charles Albon",
    role: "Scrum Master",
    department: "product",
    status: "offline",
    email: "charles@team.io",
    skills: ["Agile", "Sprint Planning", "Team Facilitation"],
    hireDate: "2020-05-12",
  },
  {
    id: "8",
    name: "Kimi Bearman",
    role: "Frontend Engineer",
    department: "engineering",
    status: "online",
    email: "kimi@team.io",
    skills: ["React", "TypeScript", "CSS"],
    hireDate: "2024-12-12",
  },
];
